### ISSUE TITLE
Improve registry approach

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid#9]
Can we use some sort of textual switch for each pubid flavor to register themselves?

e.g.
* pubid-iso registers the prefix "ISO"
* pubid-iec registers the prefix "IEC"
* etc

Then it's much easier to find the correct flavor.

_Originally posted by @ronaldtse in https://github.com/metanorma/pubid/issues/6#issuecomment-1991481370_

**Comment by mico** [comment]
@ronaldtse 
There are exceptions for IEC and ISO:
 only can be parsed by `pubid-iso`:
- `IEC/DPAS 63086-3-1`
- `IEEE/ISO/IEC 8802-1Q-2020`
- IWA 8:2009
- FprISO 105-A03
- GUIDE ISO/CEI 71:2001(F)"
- Руководство ИСО/МЭК 76
- ИСО/ПМС 1956/2 (Russian ISO identifier)
- AWI IWA 36
